version: '2'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: lots
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "33061:3306"
  server:
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
      - ./nginx/sites/local.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/local.default.conf:/etc/nginx/local.default.conf
    links:
      - php
  php:
    extends:
      file: ./base-php/base-php.yml
      service: base-php
    restart: always
    working_dir: /app
    user: '1000:1000'
    volumes:
      - ./app:/app
    links:
      - db

